// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTylRiS-wWOHI3RAtRwptWZd4DXwoyoug',
    appId: '1:603765115134:web:075aac4b634477b9d37daf',
    messagingSenderId: '603765115134',
    projectId: 'commcart-16',
    authDomain: 'commcart-16.firebaseapp.com',
    storageBucket: 'commcart-16.firebasestorage.app',
    measurementId: 'G-636HP42YBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0w1a4zaNV1P4ABcsWyOXTjLYCejjzDFM',
    appId: '1:603765115134:android:5e82bd89544679b2d37daf',
    messagingSenderId: '603765115134',
    projectId: 'commcart-16',
    storageBucket: 'commcart-16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2fIGTHw39xqmwU4BwBVtjj-B_870EBu8',
    appId: '1:603765115134:ios:9c7ee9883397ecf7d37daf',
    messagingSenderId: '603765115134',
    projectId: 'commcart-16',
    storageBucket: 'commcart-16.firebasestorage.app',
    iosBundleId: 'com.commcart.commcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2fIGTHw39xqmwU4BwBVtjj-B_870EBu8',
    appId: '1:603765115134:ios:9c7ee9883397ecf7d37daf',
    messagingSenderId: '603765115134',
    projectId: 'commcart-16',
    storageBucket: 'commcart-16.firebasestorage.app',
    iosBundleId: 'com.commcart.commcart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTylRiS-wWOHI3RAtRwptWZd4DXwoyoug',
    appId: '1:603765115134:web:845e220bbcba73f9d37daf',
    messagingSenderId: '603765115134',
    projectId: 'commcart-16',
    authDomain: 'commcart-16.firebaseapp.com',
    storageBucket: 'commcart-16.firebasestorage.app',
    measurementId: 'G-9SGCC6X4JY',
  );
}
